package pupket.togedogserver.domain.dog.constant;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import pupket.togedogserver.domain.dog.service.DogTypeDeserializer;
import pupket.togedogserver.global.exception.ExceptionCode;
import pupket.togedogserver.global.exception.customException.DogException;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@JsonDeserialize(using = DogTypeDeserializer.class)
public enum DogType {
    AFFENPINSCHER("아펜핀셔"),
    AFGHAN_HOUND("아프간 하운드"),
    AIREDALE_TERRIER("에어데일 테리어"),
    AKITA("아키타"),
    ALASKAN_MALAMUTE("알래스칸 말라뮤트"),
    AMERICAN_BULLDOG("아메리칸 불독"),
    AMERICAN_BULLY("아메리칸 불리"),
    AMERICAN_COCKER_SPANIEL("아메리칸 코커 스패니얼"),
    AMERICAN_ENGLISH_COONHOUND("아메리칸 잉글리쉬 쿤하운드"),
    AMERICAN_ESKIMO_DOG("아메리칸 에스키모 도그"),
    AMERICAN_FOXHOUND("아메리칸 폭스하운드"),
    AMERICAN_PIT_BULL_TERRIER("아메리칸 핏불 테리어"),
    AMERICAN_STAFFORDSHIRE_TERRIER("아메리칸 스태퍼드셔 테리어"),
    AMERICAN_WATER_SPANIEL("아메리칸 워터 스패니얼"),
    ANATOLIAN_SHEPHERD_DOG("아나톨리안 셰퍼드 도그"),
    AUSTRALIAN_CATTLE_DOG("오스트레일리안 캐틀 도그"),
    AUSTRALIAN_SHEPHERD("오스트레일리안 셰퍼드"),
    AUSTRALIAN_TERRIER("오스트레일리안 테리어"),
    BASENJI("바센지"),
    BASSET_HOUND("바셋 하운드"),
    BEAGLE("비글"),
    BEARDED_COLLIE("비어디드 콜리"),
    BEAUCERON("보서롱"),
    BEDLINGTON_TERRIER("베들링턴 테리어"),
    BELGIAN_MALINOIS("벨지안 말리노이즈"),
    BELGIAN_SHEEPDOG("벨지안 쉽도그"),
    BELGIAN_TERVUREN("벨지안 터뷰런"),
    BERGAMASCO("베르가마스코"),
    BERNESE_MOUNTAIN_DOG("버니즈 마운틴 도그"),
    BICHON_FRISE("비숑 프리제"),
    BLACK_AND_TAN_COONHOUND("블랙 앤드 탄 쿤하운드"),
    BLACK_RUSSIAN_TERRIER("블랙 러시안 테리어"),
    BLOODHOUND("블러드하운드"),
    BLUETICK_COONHOUND("블루틱 쿤하운드"),
    BORDER_COLLIE("보더 콜리"),
    BORDER_TERRIER("보더 테리어"),
    BORZOI("보르조이"),
    BOSTON_TERRIER("보스턴 테리어"),
    BOUVIER_DES_FLANDRES("부비에 데 플랑드르"),
    BOXER("복서"),
    BOYKIN_SPANIEL("보이킨 스패니얼"),
    BRACCO_ITALIANO("브라코 이탈리아노"),
    BRIARD("브리아드"),
    BRITTANY("브리타니"),
    BRUSSELS_GRIFFON("브뤼셀 그리펀"),
    BULL_TERRIER("불 테리어"),
    BULLDOG("불독"),
    BULLMASTIFF("불마스티프"),
    CAIRN_TERRIER("케언 테리어"),
    CANAAN_DOG("카나안 도그"),
    CANE_CORSO("카네 코르소"),
    CARDIGAN_WELSH_CORGI("카디건 웰시 코기"),
    CAVALIER_KING_CHARLES_SPANIEL("카발리에 킹 찰스 스패니얼"),
    CESKY_TERRIER("체스키 테리어"),
    CHESAPEAKE_BAY_RETRIEVER("체서피크 베이 리트리버"),
    CHIHUAHUA("치와와"),
    CHINESE_CRESTED("차이니즈 크레스티드"),
    CHINESE_SHAR_PEI("차이니즈 샤페이"),
    CHINOOK("치눅"),
    CHOW_CHOW("차우차우"),
    CLUMBER_SPANIEL("클럼버 스패니얼"),
    COCKER_SPANIEL("코커 스패니얼"),
    COLLIE("콜리"),
    CURLY_COATED_RETRIEVER("컬리 코티드 리트리버"),
    DACHSHUND("닥스훈트"),
    DALMATIAN("달마시안"),
    DANDIE_DINMONT_TERRIER("댄디 딘몬트 테리어"),
    DOBERMAN_PINSCHER("도베르만 핀셔"),
    DOGUE_DE_BORDEAUX("도그 드 보르도"),
    ENGLISH_BULLDOG("잉글리쉬 불독"),
    ENGLISH_COCKER_SPANIEL("잉글리쉬 코커 스패니얼"),
    ENGLISH_FOXHOUND("잉글리쉬 폭스하운드"),
    ENGLISH_SETTER("잉글리쉬 세터"),
    ENGLISH_SPRINGER_SPANIEL("잉글리쉬 스프링거 스패니얼"),
    ENGLISH_TOY_SPANIEL("잉글리쉬 토이 스패니얼"),
    ENTLEBUCHER_MOUNTAIN_DOG("엔틀부허 마운틴 도그"),
    FIELD_SPANIEL("필드 스패니얼"),
    FINNISH_LAPPHUND("핀란드 라푸훈드"),
    FINNISH_SPITZ("핀란드 스피츠"),
    FLAT_COATED_RETRIEVER("플랫 코티드 리트리버"),
    FRENCH_BULLDOG("프렌치 불독"),
    GERMAN_PINSCHER("저먼 핀셔"),
    GERMAN_SHEPHERD_DOG("저먼 셰퍼드 도그"),
    GERMAN_SHORTHAIRED_POINTER("저먼 쇼트헤어드 포인터"),
    GERMAN_WIRED_HAIRED_POINTER("저먼 와이어헤어드 포인터"),
    GIANT_SCHNAUZER("자이언트 슈나우저"),
    GLEN_OF_IMAAL_TERRIER("글렌 오브 이말 테리어"),
    GOLDEN_RETRIEVER("골든 리트리버"),
    GORDON_SETTER("고든 세터"),
    GREAT_DANE("그레이트 데인"),
    GREAT_PYRENEES("그레이트 피레니즈"),
    GREATER_SWISS_MOUNTAIN_DOG("그레이터 스위스 마운틴 도그"),
    GREYHOUND("그레이하운드"),
    HARRIER("해리어"),
    HAVANESE("하바네즈"),
    IBIZAN_HOUND("이비전 하운드"),
    ICELANDIC_SHEEPDOG("아이슬란딕 쉽도그"),
    IRISH_RED_AND_WHITE_SETTER("아이리시 레드 앤 화이트 세터"),
    IRISH_SETTER("아이리시 세터"),
    IRISH_TERRIER("아이리시 테리어"),
    IRISH_WATER_SPANIEL("아이리시 워터 스패니얼"),
    IRISH_WOLFHOUND("아이리시 울프하운드"),
    ITALIAN_GREYHOUND("이탈리안 그레이하운드"),
    JAPANESE_CHIN("재패니즈 친"),
    JAPANESE_SPITZ("재패니즈 스피츠"),
    KAI_KEN("카이 켄"),
    KARELIAN_BEAR_DOG("카렐리안 베어 도그"),
    KEESHOND("케이숀드"),
    KERRY_BLUE_TERRIER("케리 블루 테리어"),
    KISHU_KEN("키슈 켄"),
    KOMONDOR("코몬도르"),
    KUVASZ("쿠바스"),
    LABRADOR_RETRIEVER("래브라도 리트리버"),
    LAGOTTO_ROMAGNOLO("라고토 로마뇰로"),
    LAKELAND_TERRIER("레이클랜드 테리어"),
    LEONBERGER("레온베르거"),
    LHASA_APSO("라사 압소"),
    LOWCHEN("로첸"),
    MALTESE("말티즈"),
    MANCHESTER_TERRIER("맨체스터 테리어"),
    MASTIFF("마스티프"),
    MINIATURE_AMERICAN_SHEPHERD("미니어처 아메리칸 셰퍼드"),
    MINIATURE_BULL_TERRIER("미니어처 불 테리어"),
    MINIATURE_PINSCHER("미니어처 핀셔"),
    MINIATURE_POODLE("미니어처 푸들"),
    MINIATURE_SCHNAUZER("미니어처 슈나우저"),
    MUDI("무디"),
    NEAPOLITAN_MASTIFF("네오폴리탄 마스티프"),
    NEDERLANDSE_KOOIKERHONDJE("네덜란더스 코이케르혼제"),
    NEWFOUNDLAND("뉴펀들랜드"),
    NORFOLK_TERRIER("노퍽 테리어"),
    NORWEGIAN_BUHUND("노르웨이안 부훈드"),
    NORWEGIAN_ELKHOUND("노르웨이안 엘크하운드"),
    NORWEGIAN_LUNDEHUND("노르웨이안 룬데훈드"),
    NORWICH_TERRIER("노리치 테리어"),
    NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER("노바 스코셔 덕 톨링 리트리버"),
    OLD_ENGLISH_SHEEPDOG("올드 잉글리쉬 쉽도그"),
    OTTERHOUND("오터하운드"),
    PAPILLON("파피용"),
    PARSON_RUSSELL_TERRIER("파슨 러셀 테리어"),
    PEKINGESE("페키니즈"),
    PEMBROKE_WELSH_CORGI("펨브룩 웰시 코기"),
    PERRO_DE_PRESA_CANARIO("페로 데 프레사 카나리오"),
    PETIT_BASSET_GRIFFON_VENDEEN("프티 바셋 그리퐁 방데엔"),
    PHARAOH_HOUND("파라오 하운드"),
    PLOTT("플로트"),
    POINTER("포인터"),
    POLISH_LOWLAND_SHEEPDOG("폴리시 로우랜드 쉽도그"),
    POMERANIAN("포메라니안"),
    POODLE("푸들"),
    PORTUGUESE_PODENGO("포르투게즈 포덴고"),
    PORTUGUESE_WATER_DOG("포르투게즈 워터 도그"),
    PUG("퍼그"),
    PULI("풀리"),
    PUMI("푸미"),
    PYRENEAN_MASTIFF("피레니안 마스티프"),
    PYRENEAN_SHEPHERD("피레니안 셰퍼드"),
    RAFEIRO_DO_ALENTEJO("라페이로 도 알렌테조"),
    RAT_TERRIER("랫 테리어"),
    REDBONE_COONHOUND("레드본 쿤하운드"),
    RHODESIAN_RIDGEBACK("로디지안 리지백"),
    ROTTWEILER("로트와일러"),
    RUSSELL_TERRIER("러셀 테리어"),
    SAINT_BERNARD("세인트 버나드"),
    SALUKI("살루키"),
    SAMOYED("사모예드"),
    SCHIPPERKE("스키퍼키"),
    SCOTTISH_DEERHOUND("스코티시 디어하운드"),
    SCOTTISH_TERRIER("스코티시 테리어"),
    SEALYHAM_TERRIER("실리엄 테리어"),
    SHETLAND_SHEEPDOG("쉘티"),
    SHIBA_INU("시바 이누"),
    SHIH_TZU("시추"),
    SIBERIAN_HUSKY("시베리안 허스키"),
    SILKY_TERRIER("실키 테리어"),
    SKYE_TERRIER("스카이 테리어"),
    SLOUGHI("슬루기"),
    SMOOTH_FOX_TERRIER("스무스 폭스 테리어"),
    SOFT_COATED_WHEATEN_TERRIER("소프트 코티드 휘튼 테리어"),
    SPANISH_WATER_DOG("스패니시 워터 도그"),
    SPINONE_ITALIANO("스피노네 이탈리아노"),
    STAFFORDSHIRE_BULL_TERRIER("스태퍼드셔 불 테리어"),
    STANDARD_POODLE("스탠다드 푸들"),
    STANDARD_SCHNAUZER("스탠다드 슈나우저"),
    SUSSEX_SPANIEL("서식스 스패니얼"),
    SWEDISH_VALLHUND("스웨디시 발훈드"),
    TIBETAN_MASTIFF("티베탄 마스티프"),
    TIBETAN_SPANIEL("티베탄 스패니얼"),
    TIBETAN_TERRIER("티베탄 테리어"),
    TOY_FOX_TERRIER("토이 폭스 테리어"),
    TREEING_WALKER_COONHOUND("트리잉 워커 쿤하운드"),
    VIZSLA("비즐라"),
    WEIMARANER("와이마라너"),
    WELSH_SPRINGER_SPANIEL("웰시 스프링어 스패니얼"),
    WELSH_TERRIER("웰시 테리어"),
    WEST_HIGHLAND_WHITE_TERRIER("웨스트 하이랜드 화이트 테리어"),
    WHIPPET("휘핏"),
    WIRE_FOX_TERRIER("와이어 폭스 테리어"),
    WIREHAIRED_POINTING_GRIFFON("와이어헤어드 포인팅 그리폰"),
    WIREHAIRED_VIZSLA("와이어헤어드 비즐라"),
    XOLOITZCUINTLI("솔로이츠쿠인틀리"),
    YORKSHIRE_TERRIER("요크셔 테리어");

    final private String type;

    DogType(String breed) {
        this.type = breed;
    }

    @JsonValue
    public String getType() {
        return type;
    }

    public static DogType nameOf(String name) {
        for (DogType data : DogType.values()) {
            if (data.getType().equals(name)) {
                return data;
            }
        }
        throw new DogException(ExceptionCode.INVALID_ENUM_PARAMETER);
    }

}

